### ISSUE TITLE
Broken checkpoint downloads inside install.sh

### ISSUE THREAD

**Issue by MatousKundrik** [riccardomarin/NICP#1]
Checkpoint download links hQWV & LYSr within [install.sh](https://github.com/riccardomarin/NICP/blob/main/install.sh) appear to no longer be working. Would it be possible to get these reuploaded elsewhere.

Thanks

**Comment by riccardomarin** [comment]
Hi @MatousKundrik ,
Thanks for pointing out! I updated the links. Let me know if everything is fine now.

**Comment by MatousKundrik** [comment]
> Hi @MatousKundrik , Thanks for pointing out! I updated the links. Let me know if everything is fine now.

Yep can confirm links are now working as expected - thanks! 👍
