### ISSUE TITLE
SMPL data

### ISSUE THREAD

**Issue by Akola-Mbey-Denis** [riccardomarin/NICP#11]
Hello,

Thanks for this work.

Please where can I find the SMPLH data to download? Thanks in advance.

**Comment by yunhanwang1105** [comment]
You could go to this link: https://mano.is.tue.mpg.de/download.php
And register an account then download the **Extended SMPL+H model**

**Comment by riccardomarin** [comment]
Thanks, @yunhanwang1105, for providing the answer! I will make this more explicit in the readme
