### ISSUE TITLE
No module named 'utils_cop'

### ISSUE THREAD

**Issue by SuperWatch** [riccardomarin/NICP#4]
error：
from utils_cop.prior import MaxMixturePrior
ModuleNotFoundError: No module named 'utils_cop'

'utils_cop' is set in .gitignore.

can you update it ?

**Comment by riccardomarin** [comment]
Hi @SuperWatch ,
Thank you for your message.

The 'utils_cop' is a folder created by running the install.sh script ([Line 43](https://github.com/riccardomarin/NICP/blob/7a1447b240d6f47b4d78fffb9dfa933e80a968e5/install.sh#L43)). 

Let me know if running the command solves your issue.
