### ISSUE TITLE
Inference on a sample pointcloud completely fails

### ISSUE THREAD

**Issue by AntiLibrary5** [riccardomarin/NICP#5]
Hi,
I liked reading the paper. Nice ideas. I wanted to try firsthand. I use a pointcloud as input in the spirit of Fig 5 in the paper with following command.
`PYTHONPATH=. python ./src/lvd_templ/evaluation/evaluation_benchmark.py`

##### input pointcloud, out_ss, out__ss_cham_0_+D for my sample
<img src="https://github.com/user-attachments/assets/7a9a4f73-6cd8-44ce-8405-2c9f716534bf" alt="Description" width="250px">
<img src="https://github.com/user-attachments/assets/9fa95c39-8804-4afe-875c-ce40d6c957ce" alt="Description" width="250px">
<img src="https://github.com/user-attachments/assets/735e49f9-4277-4839-afba-f878c7e45a61" alt="Description" width="250px">

##### out__ss_cham_0_+D for test_scan_044
<img src="https://github.com/user-attachments/assets/18c0a990-9b94-4636-a219-7ef7041e72d4" alt="Description" width="250px">

As we see, it worked for the example in the demo folder provided, but fails for the sample I use (from amass). Are there hyperparameters to be tweaked? If not, why do you think NICP fails here?

Thank you.

**Comment by riccardomarin** [comment]
Hi @AntiLibrary5,
Thank you for your message and your interest!

The result is definitely not what is expected: I observe similar results when the input point cloud is not vertically oriented correctly. 
Could you open in the same MeshLab window your input PC and the provided demo and verify that their "floors" are kind of aligned?

**Comment by AntiLibrary5** [comment]
I see, it was probably due to the "y-axis alignment" issue? Adding the global_rot arg fixes it :) thanks. Just a follow up question, `out_ss.ply` is smpl fitting, can we access the parameters? or is it only the template morphed to the scan? In the paper, it mentions "we fit SMPL as in LVD"

![image](https://github.com/user-attachments/assets/8c421e39-5947-4bc0-a122-4e71f22a99fb)
![image](https://github.com/user-attachments/assets/1e9bf2d5-f70e-4ebf-9d80-97fd5b1136d7)

**Comment by riccardomarin** [comment]
Glad it worked! :)

Yes, the code also returns the SMPL parameters in a file called "loss_out_ss.npy" in the output folder.  Loading it, you will find the parameters corresponding to out_ss.ply. For reference of the keys contained in the .npy, you can check [here](https://github.com/riccardomarin/NICP/blob/7a1447b240d6f47b4d78fffb9dfa933e80a968e5/src/lvd_templ/evaluation/utils.py#L387).

If you want the SMPL parameters also for the step after the chamfer refinement, you can uncomment [these lines](https://github.com/riccardomarin/NICP/blob/7a1447b240d6f47b4d78fffb9dfa933e80a968e5/src/lvd_templ/evaluation/evaluation_benchmark.py#L262) of the script.

**Comment by AntiLibrary5** [comment]
Awesome. Thanks!
