### ISSUE TITLE
About training dataset

### ISSUE THREAD

**Issue by boqian-li** [riccardomarin/NICP#7]
Hi, I am trying to reproduce the experiments in the paper. You said "To train the NF, we leverage the large MoCap AMASS dataset of adopting the official splits. "However, there are some different versions of dataset split on the web. 
So could you tell me the specific amass_data_split you used to train NF? 
Thanks!

**Comment by riccardomarin** [comment]
Hi @boqian-li ,
Thank you for your interest in our work.

In the repository, you can also find the training and preprocessing code for the data. Although not yet fully polished, it should contain all the details for reproducing the experiments.

About AMASS split, you can find it here:
https://github.com/riccardomarin/NICP/blob/0882749b569dd422063abd941e70bd6d290f7242/training/data_preprocessing/prepare_data_corr.py#L280

**Comment by boqian-li** [comment]
Hi @riccardomarin thank you!
